// Generated by Melange
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var StoryData = require("./StoryData.js");
var CommentList = require("./CommentList.js");

require("src/CommentsPage.css");

function CommentsPage(Props) {
  var id = Props.id;
  var match = React.useReducer((function (_state, action) {
          return {
                  story_with_comments: action._0
                };
        }), {
        story_with_comments: undefined
      });
  var dispatch = match[1];
  var renderTitle = function (story) {
    var title = React.createElement("h2", {
          className: "CommentsPage_title"
        }, story.title);
    var url = story.url;
    return React.createElement("div", undefined, url !== undefined ? React.createElement("a", {
                      className: "CommentsPage_titleLink",
                      href: url
                    }, title) : title);
  };
  var renderByline = function (story) {
    var time = story.time;
    var by = story.by;
    return React.createElement("div", undefined, React.createElement("span", undefined, String(story.score)), " points", React.createElement("span", undefined, React.createElement("span", undefined, " submitted " + time + " by " + by)));
  };
  React.useEffect((function () {
          StoryData.fetchStoryWithComments(id, (function (data) {
                  return Curry._1(dispatch, /* Loaded */{
                              _0: data
                            });
                }));
          
        }), []);
  var story = match[0].story_with_comments;
  return React.createElement("div", {
              className: "CommentsPage_container"
            }, story !== undefined ? React.createElement("div", undefined, renderTitle(story), renderByline(story), React.createElement(CommentList.make, {
                        story: story
                      })) : "loading");
}

var make = CommentsPage;

exports.make = make;
/*  Not a pure module */
