// Generated by Melange
'use strict';

var App = require("./App.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var RescriptReactRouter = require("@rescript/react/./src/RescriptReactRouter.js");
var ReactDomExperimental = require("./bindings/ReactDomExperimental.js");
var RegisterServiceWorker = require("src/registerServiceWorker");

RegisterServiceWorker();

require("src/Index.css");

var root = ReactDomExperimental.createRootWithId("root");

if (root !== undefined) {
  Caml_option.valFromOption(root).render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }));
  RescriptReactRouter.push("");
}

/*  Not a pure module */
