// Generated by Melange
'use strict';

var React = require("react");
var RescriptReactRouter = require("@rescript/react/./src/RescriptReactRouter.js");

function handleClick(href, $$event) {
  if (!$$event.defaultPrevented) {
    $$event.preventDefault();
    return RescriptReactRouter.push(href);
  }
  
}

function Link(Props) {
  var href = Props.href;
  var classNameOpt = Props.className;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("a", {
              className: className,
              href: href,
              onClick: (function ($$event) {
                  return handleClick(href, $$event);
                })
            }, children);
}

var make = Link;

exports.handleClick = handleClick;
exports.make = make;
/* react Not a pure module */
