// Generated by Melange
'use strict';

var Link = require("./Link.js");
var React = require("react");

require("src/NotFound.css");

var notFoundImage = require("src/notfound404.png");

function NotFound(Props) {
  return React.createElement("div", {
              className: "NotFound_container"
            }, React.createElement("div", {
                  className: "NotFound_image"
                }, React.createElement("img", {
                      alt: "Page not found",
                      src: notFoundImage
                    })), React.createElement("div", {
                  className: "NotFound_text"
                }, React.createElement("span", undefined, "The page you're looking for can't be found. Go home by "), React.createElement(Link.make, {
                      href: "/",
                      children: "clicking here!"
                    })));
}

var make = NotFound;

exports.notFoundImage = notFoundImage;
exports.make = make;
/*  Not a pure module */
