// Generated by Melange
'use strict';

var Link = require("./Link.js");
var React = require("react");

require("src/StoryListItem.css");

var commentIcon = require("src/comment.png");

function StoryListItem(Props) {
  var story = Props.story;
  var index = Props.index;
  var renderIndex = function (param) {
    return React.createElement("aside", {
                className: "StoryListItem_storyIndex"
              }, String(index + 1 | 0));
  };
  var renderTitle = function (param) {
    var content = story.title;
    var url = story.url;
    return React.createElement("header", {
                className: "StoryListItem_storyTitle"
              }, url !== undefined ? React.createElement("a", {
                      className: "StoryListItem_link",
                      href: url,
                      target: "_blank"
                    }, content) : React.createElement(Link.make, {
                      href: "/comments/" + String(story.id),
                      className: "StoryListItem_link",
                      children: content
                    }));
  };
  var renderByline = function (param) {
    var time = story.time;
    var by = story.by;
    return React.createElement("div", {
                className: "StoryListItem_row StoryListItem_byline"
              }, React.createElement("span", {
                    className: "StoryListItem_number"
                  }, React.createElement("b", undefined, String(story.score)), " points"), React.createElement("span", {
                    className: "StoryListItem_storyTime"
                  }, " submitted " + time + " by " + by));
  };
  var renderArticleButton = function (param) {
    return React.createElement("div", {
                className: "StoryListItem_flexRow"
              }, renderIndex(undefined), React.createElement("div", {
                    className: "StoryListItem_storyCell"
                  }, renderTitle(undefined), renderByline(undefined)));
  };
  var renderCommentsButton = function (param) {
    return React.createElement("div", {
                className: "StoryListItem_commentsCell"
              }, React.createElement(Link.make, {
                    href: "/comments/" + String(story.id),
                    className: "StoryListItem_link",
                    children: null
                  }, React.createElement("div", undefined, React.createElement("img", {
                            className: "StoryListItem_icon",
                            alt: "comments",
                            src: commentIcon
                          })), React.createElement("div", undefined, React.createElement("span", {
                            className: "StoryListItem_commentsText"
                          }, React.createElement("span", {
                                className: "StoryListItem_number"
                              }, String(story.descendants)), " comments"))));
  };
  return React.createElement("div", {
              className: "StoryListItem_itemRow"
            }, renderArticleButton(undefined), renderCommentsButton(undefined));
}

var make = StoryListItem;

exports.commentIcon = commentIcon;
exports.make = make;
/*  Not a pure module */
